<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CdliModalSelector\Module'                                  => __DIR__ . '/Module.php',
    'CdliModalSelector\Controller\Datasource\ZfcUserController' => __DIR__ . '/src/CdliModalSelector/Controller/Datasource/ZfcUserController.php',
);